site_name: Lambda Documentation
nav:
  - Introduction: index.md

  - Service Status Check:
      - State List: servicescodes/statecode.md
      - DLR: servicescodes/dlr.md
      - Service Balance Check: servicescodes/balance_check.md
      - Service LookUp API: servicescodes/lookup.md
      - Bulk Service Lookup: servicescodes/bulkservice.md

  - TBO Air:
      - Search: tbo-air/search.md
      - Book: tbo-air/book.md
      - AddInfo: tbo-air/add_info.md
      - Issue: tbo-air/issue.md
      - Get Ticket Details: tbo-air/get_ticket_details.md
      - Master Data API: tbo-air/options.md

  - TBO Hotels:
      - Search: tbo-hotels/search.md
      - PreBook: tbo-hotels/pre-book.md
      - Issue: tbo-hotels/issue.md
      - Get Ticket Details: tbo-hotels/get-ticket-details.md
      - Master Data API: tbo-hotels/options.md

  - FAQ's: servicescodes/faq.md


theme:
  name: material
  custom_dir: overrides
  favicon: "img/favicon.ico"
  icon:
    logo: "img/lambda_logo"
extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css
  - style/custom.css
  - style/extra.css

docs_dir: content
site_dir: docs
edit_uri: "edit/main/content/"
copyright: "Copyright &copy; 2025 Lambda Payments"

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - codehilite
  - pymdownx.details
  - pymdownx.superfences

# Uncomment and install any necessary plugins if needed
# plugins:
#   - search
#   - social